# Generated by Django 4.1.5 on 2023-01-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcuser",
            name="username",
            field=models.CharField(max_length=32, verbose_name="사용자명"),
        ),
    ]
