# Generated by Django 4.1.5 on 2023-01-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_board_tag_alter_board_writer"),
    ]

    operations = [
        migrations.RenameField(model_name="board", old_name="tag", new_name="tags",),
    ]
